apiVersion: v1
kind: Service
metadata:
  name: letterme-service
spec:
  selector:
    app: letterme
  ports:
    - name: hello
      protocol: TCP
      port: 8080
      nodePort: 30001
  type: NodePort